version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
